# Generated by Django 5.2.7 on 2025-10-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
